<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Homework 4</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ece42c8223ec2bf36298a08f122c9a68.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Homework 4</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="preamble" class="level1">
<h1>Preamble</h1>
<p>This homework practices with application programming interfaces (APIs) and exploratory data analyses (EDAs).</p>
</section>
<section id="task-1-querying-an-api-and-a-tidy-style-function" class="level1">
<h1>Task 1: Querying an API and a Tidy-Style Function</h1>
<p>This task makes use of the website newsapi.org. Having registered for a key using my NCSU email, we now do the following.</p>
<ol type="1">
<li>Use <code>GET()</code> from the <code>httr</code> package to return information about a topic I am interested in recently (i.e., within the past <span class="math inline">\(30\)</span> days, per the free account limit): the Ebola virus outbreak in the Democratic Republic of Congo (DRC) and Uganda.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(httr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>ebola_news <span class="ot">&lt;-</span> <span class="fu">GET</span>(<span class="st">"https://newsapi.org/v2/everything?q=ebola&amp;from=2026-05-15&amp;language=en&amp;pageSize=50&amp;apiKey=e7e98c8f31914c04a5d15115a45ea6e3"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>ebola_news</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Response [https://newsapi.org/v2/everything?q=ebola&amp;from=2026-05-15&amp;language=en&amp;pageSize=50&amp;apiKey=e7e98c8f31914c04a5d15115a45ea6e3]
  Date: 2026-06-15 22:13
  Status: 200
  Content-Type: application/json; charset=utf-8
  Size: 41.5 kB</code></pre>
</div>
</div>
<p>(For future reference, I cannot load multiple libraries in the same <code>library</code> call separated by commas.)</p>
<ol start="2" type="1">
<li>We now parse what was returned to recover information about article information.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jsonlite)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>ebola_parsed <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">rawToChar</span>(ebola_news<span class="sc">$</span>content))</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(ebola_parsed)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 3
 $ status      : chr "ok"
 $ totalResults: int 3311
 $ articles    :'data.frame':   50 obs. of  8 variables:
  ..$ source     :'data.frame': 50 obs. of  2 variables:
  .. ..$ id  : chr [1:50] NA NA NA NA ...
  .. ..$ name: chr [1:50] "BBC News" "BBC News" "BBC News" "BBC News" ...
  ..$ author     : chr [1:50] NA NA NA NA ...
  ..$ title      : chr [1:50] "'Speed, money and compassion' - lessons from an Ebola survivor and other experts" "Red Cross volunteers die from suspected Ebola in DR Congo" "'Ebola has tortured us': Fear grips eastern DR Congo as deadly virus spreads" "At least six Americans exposed to Ebola in DR Congo, US media report" ...
  ..$ description: chr [1:50] "Those caught up in West Africa's Ebola outbreak a decade ago on how best to tackle the current epidemic." "They are thought to have caught the virus before the outbreak was identified, the Red Cross says." "The health minister has acknowledged that medics are playing catch-up with the virus after being slow to detect it." "One of the six Americans believed to have been exposed is experiencing symptoms, according to media reports." ...
  ..$ url        : chr [1:50] "https://www.bbc.com/news/articles/cj3p2rdx0l8o" "https://www.bbc.com/news/articles/c759knxln0wo" "https://www.bbc.com/news/articles/cvgzj0pqpyyo" "https://www.bbc.com/news/articles/cq6pz60p996o" ...
  ..$ urlToImage : chr [1:50] "https://ichef.bbci.co.uk/news/1024/branded_news/68b3/live/8445c700-55d0-11f1-8b8c-6d33e1d5abb6.jpg" "https://ichef.bbci.co.uk/news/1024/branded_news/f4e9/live/1fde0380-56bc-11f1-89a3-d1f559421220.jpg" "https://ichef.bbci.co.uk/news/1024/branded_news/c8bb/live/9d165df0-5394-11f1-82e5-bb1c743931bd.jpg" "https://ichef.bbci.co.uk/news/1024/branded_news/3195/live/9d886d70-5293-11f1-8a13-e989d3b4b6c8.jpg" ...
  ..$ publishedAt: chr [1:50] "2026-05-22T23:07:41Z" "2026-05-23T17:15:09Z" "2026-05-19T18:05:26Z" "2026-05-18T10:07:57Z" ...
  ..$ content    : chr [1:50] "Three days after the funeral, he fell sick with Ebola, finding himself turning from healthcare worker to patien"| __truncated__ "The same day, the African Centres for Disease Control warned 10 other countries on the continent were at risk o"| __truncated__ "Following a visit to Ituri province, the epicentre of the outbreak, over the weekend, Congolese Health Minister"| __truncated__ "The disease spread to a number of countries within and outside of West Africa, including Guinea, Sierra Leone, "| __truncated__ ...</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Lastly, we construct a function allowing a user to more easily query this API by <code>topic</code>, <code>earliest_date</code>, and <code>API_key</code>. For this problem, we will return a <code>vector</code> of the article titles.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>news_search <span class="ot">&lt;-</span> <span class="cf">function</span>(topic,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">earliest_date =</span> <span class="st">"2026-05-16"</span>,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">API_key =</span> <span class="st">"e7e98c8f31914c04a5d15115a45ea6e3"</span>){</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  format_query <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">"https://newsapi.org/v2/everything?q="</span>,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>                         topic,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>                         <span class="st">"&amp;from="</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>                         earliest_date,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>                         <span class="st">"&amp;language=en&amp;pageSize=50&amp;apiKey="</span>,</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>                         API_key)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  news_query <span class="ot">&lt;-</span> <span class="fu">GET</span>(format_query)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>  news_parsed <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">rawToChar</span>(news_query<span class="sc">$</span>content))</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  news_parsed<span class="sc">$</span>articles<span class="sc">$</span>title</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>First, let us query on “AI”.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">news_search</span>(<span class="st">"AI"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "AI leaders call for tougher protections against AI-aided bioweapons"               
 [2] "Microsoft AI chief walks back comments about AI taking over white-collar work"     
 [3] "Google’s AI search is so broken it can ‘disregard’ what you’re looking for"        
 [4] "YouTube is putting AI labels where you’ll actually see them"                       
 [5] "The Endless AI guitar pedal has potential"                                         
 [6] "Apple announces visionOS 27 with Siri AI"                                          
 [7] "Let us filter AI slop, you cowards"                                                
 [8] "We Asked the ‘Future of Truth’ Author to Explain How He Used AI. It Didn’t Go Well"
 [9] "Spotify Studio’s AI agent creates a daily podcast just for you"                    
[10] "Pope Leo calls for being ‘profoundly human’ in the age of AI"                      
[11] "Apple’s best AI idea looks a lot like vibe coding"                                 
[12] "Apple wants Europe to blink"                                                       
[13] "Apple’s new Siri AI knows when to shut up"                                         
[14] "The AI Era Is Creating a Bug Hunting Arms Race"                                    
[15] "The Gulf’s AI Boom Has an Undersea Cable Problem"                                  </code></pre>
</div>
</div>
<p>Finally, let us query, within the past week, on the “NBA”.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">news_search</span>(<span class="st">"NBA"</span>, <span class="st">"2026-06-08"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Five people injured in stabbing at New York City's Penn Station"                                                        
 [2] "Knicks fans go wild as New York team makes biggest comeback in NBA Finals history"                                      
 [3] "Where to watch Knicks vs Spurs game 5: NBA Finals live stream, channel, odds, venue"                                    
 [4] "Sports are pricing out the fans who made them rich"                                                                     
 [5] "WATCH: NY Knicks are 'playing like a veteran team': Analyst"                                                            
 [6] "Taylor Swift, Michael J. Fox and more attend Knicks-Spurs NBA Finals Game 4 at MSG"                                     
 [7] "San Antonio Spurs win 115-111 victory over New York Knicks in Game 3"                                                   
 [8] "WATCH: Game 4 could reshape the NBA Finals narrative"                                                                   
 [9] "WATCH: The historic 2026 NBA Finals and what comes next"                                                                
[10] "Suspect sought after teen beaten into coma near MSG after Knicks' Game 4 win: Police"                                   
[11] "Pedestrian traffic restricted in Midtown Manhattan as Trump's NBA Finals trip spurs intense security"                   
[12] "Photos: Knicks Fans Celebrate Their NBA Championship"                                                                   
[13] "OG Anunoby's Accidental Instagram Live From The Knicks Locker Room Has Me Absolutely Dying Because We've All Been There"
[14] "WATCH: New York coffee shop goes viral with Knicks spirit"                                                              
[15] "New York hosts San Antonio with 2-1 series lead"                                                                        
[16] "WATCH: Police on alert for malicious activity as Knicks host NBA Finals"                                                
[17] "WATCH: Jalen Brunson and dad on unbreakable father-son bond through basketball"                                         
[18] "WATCH: What just happened? Inside the New York Knicks' historic comeback"                                               
[19] "WATCH: Chase lights up New York City for the NBA Finals"                                                                
[20] "'The greatest day of my life' - Knicks fans celebrate in San Antonio"                                                   
[21] "WATCH: Rowdy fans pour into streets after NBA Finals game in NYC"                                                       
[22] "Trump to cheer on Knicks at NBA Finals game in New York City"                                                           
[23] "The Latest: Trump dismisses idea that Iran betrays his ‘no new wars’ campaign message"                                  
[24] "Knicks complete record rally from 29 points down and beat Spurs"                                                        
[25] "Jordyn Woods' Knicks bag isn't just lucky. It's smart business."                                                        
[26] "As Trump Fell Asleep At The NBA Finals, Mayor Mamdani Enjoyed The Knicks Game In The Nosebleed Seats"                   
[27] "Trump And MAGA Are Not Exactly Coping...Well With The Extreme Booing He Receieved At The NBA Finals"                    
[28] "Why Do Some NBA Players Seem to Hate Gatorade?"                                                                         
[29] "Flip in win probability for Knicks vs. Spurs"                                                                           
[30] "The City That Never Sleeps Got Its NBA Win Streak Cursed by the Queens Man Who Did"                                     
[31] "MiB: Joe McLean, MAI Capital"                                                                                           
[32] "WATCH: Hiker survives grizzly bear attack: 'I thought...this is it'"                                                    
[33] "WATCH: Celebrating 30 years of 'Toy Story' and beyond"                                                                  
[34] "To find the World Cup's Cinderellas, we have to start with the group stage"                                             
[35] "Trump says pilots are fine after U.S. helicopter crashes near Strait of Hormuz"                                         
[36] "WATCH: 2026 Tony Awards biggest moments"                                                                                
[37] "WATCH: Taylor Swift's new 'Toy Story 5' single sets&nbsp;multiple records"                                                   
[38] "WATCH: 3 soccer fans bike 11,000 miles for World Cup"                                                                   
[39] "WATCH: Stanley Cup Final goes to Game 6"                                                                                
[40] "WATCH: Spice reflects on legacy, culture and Caribbean American Heritage Month"                                         
[41] "WATCH: Preview of the Los Angeles Pride parade"                                                                         
[42] "Knicks NBA Championship Merch Includes Official Locker Room T-Shirt, Signed Jalen Brunson Basketballs"                  
[43] "8 Things That Didn’t Exist When the Knicks Last Won the Championship"                                                   
[44] "Trump Booed Loudly During National Anthem at Knicks Finals Game"                                                        
[45] "Wu-Tang Clan Hit the Court for NBA Finals Game 4 Halftime Show"                                                         
[46] "Late-Night Hosts Take Aim at Trump’s Knicks Game Appearance: ‘He Hit Them With a Jinx’"                                 
[47] "Cardi B Shows Out for New York During NBA Finals Game 3 Halftime&nbsp;Show"                                                  
[48] "All the Celebrities Flocking to Watch Knicks vs. Spurs in the NBA Finals"                                               
[49] "27.5\" WILSON NBA DRV Series Basketball (Size 5) $10"                                                                   
[50] "Knicks beat Spurs after record NBA Finals comeback"                                                                     </code></pre>
</div>
</div>
</section>
<section id="task-2-summarizing-roller-coaster-data" class="level1">
<h1>Task 2: Summarizing Roller Coaster Data</h1>
<p>For this task, we use the data located <a href="https://www4.stat.ncsu.edu/online/datasets/635USrollercoasters.csv">here</a>.</p>
<section id="read-in-and-convert-to-factors" class="level2">
<h2 class="anchored" data-anchor-id="read-in-and-convert-to-factors">Read In and Convert to Factors</h2>
<p>First we read in the data, amending the column names to standard format.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>columns <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"coaster"</span>, <span class="st">"park"</span>, <span class="st">"city"</span>, <span class="st">"state"</span>, <span class="st">"census_region"</span>,</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>             <span class="st">"year_opened"</span>, <span class="st">"age_group"</span>, <span class="st">"top_speed"</span>, <span class="st">"max_height"</span>, <span class="st">"scale"</span>,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>             <span class="st">"type"</span>, <span class="st">"design"</span>, <span class="st">"drop"</span>, <span class="st">"length"</span>, <span class="st">"duration"</span>,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>             <span class="st">"inversions"</span>, <span class="st">"number_of_inversions"</span>, <span class="st">"make"</span>, <span class="st">"latitude"</span>, <span class="st">"longitude"</span>,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>             <span class="st">"boundary"</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>roller_coaster <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://www4.stat.ncsu.edu/online/datasets/635USrollercoasters.csv"</span>,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">col_names =</span> columns,</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">show_col_types =</span> <span class="cn">FALSE</span>,</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>                  <span class="at">skip =</span> <span class="dv">1</span>,</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Then convert the appropriate variables (columns), viz., <code>census_region</code>, <code>age_group</code>, <code>scale</code>, <code>type</code>, and <code>design</code>, to factors; and convert an additional column, <code>inversions</code>, to <code>logi</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>roller_coaster <span class="ot">&lt;-</span> roller_coaster <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(census_region, age_group, scale, type, design),</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>                as.factor))</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(roller_coaster<span class="sc">$</span>inversions)){</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  roller_coaster<span class="sc">$</span>inversions[i] <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(roller_coaster<span class="sc">$</span>inversions[i] <span class="sc">==</span> <span class="st">"Yes"</span>,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"True"</span>,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"False"</span>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>roller_coaster<span class="sc">$</span>inversions <span class="ot">&lt;-</span> <span class="fu">as.logical</span>(roller_coaster<span class="sc">$</span>inversions)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(roller_coaster)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [635 × 21] (S3: tbl_df/tbl/data.frame)
 $ coaster             : chr [1:635] "Adrenaline Peak" "Adventure Express" "Afterburn" "Aftershock" ...
 $ park                : chr [1:635] "Oaks Amusement Park" "Kings Island" "Carowinds" "Silverwood Theme Park" ...
 $ city                : chr [1:635] "Portland" "Mason" "Charlotte" "Athol" ...
 $ state               : chr [1:635] "Oregon" "Ohio" "North Carolina" "Idaho" ...
 $ census_region       : Factor w/ 4 levels "Midwest","Northeast",..: 4 1 3 4 3 3 2 1 1 3 ...
 $ year_opened         : num [1:635] 2018 1991 1999 2008 2010 ...
 $ age_group           : Factor w/ 3 levels "1:Older","2:Recent",..: 3 2 2 3 3 2 2 2 3 2 ...
 $ top_speed           : num [1:635] 45 35 62 65.6 22 67 35 66 48 50 ...
 $ max_height          : num [1:635] 72 63 113 192 25 ...
 $ scale               : Factor w/ 4 levels "Extreme","Family",..: 1 4 1 1 2 1 4 1 4 1 ...
 $ type                : Factor w/ 2 levels "Steel","Wood": 1 1 1 1 1 1 1 2 2 1 ...
 $ design              : Factor w/ 7 levels "Bobsled","Flying",..: 4 4 3 3 4 3 1 4 4 4 ...
 $ drop                : num [1:635] 70 47 110 177 22.5 170 20 147 80 144 ...
 $ length              : num [1:635] 1050 2963 2956 1204 628 ...
 $ duration            : num [1:635] 66 140 167 92 47 190 100 143 110 110 ...
 $ inversions          : logi [1:635] TRUE FALSE TRUE TRUE FALSE TRUE ...
 $ number_of_inversions: num [1:635] 3 0 6 3 0 6 0 0 0 4 ...
 $ make                : chr [1:635] "Gerstlauer Amusement Rides GmbH" "Arrow Dynamics" "Bolliger &amp; Mabillard" "Vekoma" ...
 $ latitude            : num [1:635] 45.5 39.4 35.3 47.9 28 ...
 $ longitude           : num [1:635] -122.7 -84.3 -80.8 -116.7 -82.6 ...
 $ boundary            : chr [1:635] "{\"type\":\"Feature\",\"properties\":{\"CENSUSAREA\":95988.013,\"NAME\":\"Oregon\",\"GEO_ID\":\"0400000US41\",\"| __truncated__ "{\"type\":\"Feature\",\"properties\":{\"CENSUSAREA\":40860.694,\"NAME\":\"Ohio\",\"GEO_ID\":\"0400000US39\",\"L"| __truncated__ "{\"type\":\"Feature\",\"properties\":{\"CENSUSAREA\":48617.905,\"NAME\":\"North Carolina\",\"GEO_ID\":\"0400000"| __truncated__ "{\"type\":\"Feature\",\"properties\":{\"CENSUSAREA\":82643.117,\"NAME\":\"Idaho\",\"GEO_ID\":\"0400000US16\",\""| __truncated__ ...</code></pre>
</div>
</div>
<p>Now we examine the data for missing values.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(roller_coaster)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      coaster           park            city           state    
 Length   :635   Length   :635   Length   :635   Length   :635  
 N.unique :482   N.unique :197   N.unique :171   N.unique : 40  
 N.blank  :  0   N.blank  :  0   N.blank  :  0   N.blank  :  0  
 Min.nchar:  2   Min.nchar:  6   Min.nchar:  3   Min.nchar:  4  
 Max.nchar: 46   Max.nchar: 47   Max.nchar: 20   Max.nchar: 14  
                                                                
                                                                
   census_region  year_opened      age_group     top_speed        max_height   
 Midwest  :134   Min.   :1920   1:Older : 69   Min.   :  6.00   Min.   :  5.0  
 Northeast:156   1st Qu.:1995   2:Recent:190   1st Qu.: 28.50   1st Qu.: 28.0  
 South    :223   Median :2002   3:Newest:376   Median : 45.00   Median : 64.3  
 West     :122   Mean   :1999                  Mean   : 42.24   Mean   : 76.8  
                 3rd Qu.:2013                  3rd Qu.: 55.00   3rd Qu.:109.0  
                 Max.   :2020                  Max.   :128.00   Max.   :456.0  
                                               NAs    :74       NAs    :8      
     scale        type           design         drop            length    
 Extreme:269   Steel:530   Bobsled  :  4   Min.   :  0.00   Min.   :  48  
 Family :178   Wood :105   Flying   :  9   1st Qu.: 25.00   1st Qu.: 900  
 Kiddie : 28               Inverted : 42   Median : 70.00   Median :1490  
 Thrill :160               Sit Down :560   Mean   : 77.18   Mean   :1938  
                           Stand Up :  4   3rd Qu.:108.50   3rd Qu.:2800  
                           Suspended:  7   Max.   :418.00   Max.   :7359  
                           Wing     :  9   NAs    :128      NAs    :33    
    duration   inversions      number_of_inversions        make    
 Min.   : 20   Mode :logical   Min.   :0.0000       Length   :635  
 1st Qu.: 70   FALSE:465       1st Qu.:0.0000       N.unique : 53  
 Median :101   TRUE :170       Median :0.0000       N.blank  :  0  
 Mean   :106                   Mean   :0.9213       Min.nchar:  4  
 3rd Qu.:130                   3rd Qu.:1.0000       Max.nchar: 36  
 Max.   :540                   Max.   :8.0000       NAs      : 36  
 NAs    :66                                                        
    latitude       longitude            boundary    
 Min.   :26.55   Min.   :-122.94   Length   :  635  
 1st Qu.:34.47   1st Qu.: -97.15   N.unique :   41  
 Median :38.51   Median : -84.31   N.blank  :    0  
 Mean   :37.69   Mean   : -89.46   Min.nchar: 6568  
 3rd Qu.:40.97   3rd Qu.: -77.46   Max.nchar:32759  
 Max.   :47.92   Max.   : -70.39                    
                                                    </code></pre>
</div>
</div>
<p>Of the <span class="math inline">\(9\)</span> numeric variables, <span class="math inline">\(5\)</span> have missing values: <code>top_speed</code>, <code>max_height</code>, <code>drop</code>, <code>length</code>, and <code>duration</code>. None of the <code>char</code> or <code>factor</code> variables appear to have missing values.</p>
</section>
<section id="categorical-variables" class="level2">
<h2 class="anchored" data-anchor-id="categorical-variables">Categorical Variables</h2>
<p>Now we examine a few comparative tables and plots for the categorical data.</p>
<ul>
<li>First we create a one-way, two-way, and three-way contingency table in base <code>R</code> for the <code>factor</code> variables <code>census_region</code>, <code>scale</code>, and <code>age_group</code>, respectively.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(roller_coaster<span class="sc">$</span>census_region) <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">addmargins</span>()  <span class="co"># includes totals across rows, columns, and table levels</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  Midwest Northeast     South      West       Sum 
      134       156       223       122       635 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(roller_coaster<span class="sc">$</span>census_region, roller_coaster<span class="sc">$</span>scale) <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">addmargins</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           
            Extreme Family Kiddie Thrill Sum
  Midwest        61     32      8     33 134
  Northeast      62     49      7     38 156
  South          92     68      6     57 223
  West           54     29      7     32 122
  Sum           269    178     28    160 635</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>three_way <span class="ot">&lt;-</span> <span class="fu">table</span>(roller_coaster<span class="sc">$</span>census_region, roller_coaster<span class="sc">$</span>scale,</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>                   roller_coaster<span class="sc">$</span>age_group) <span class="sc">|&gt;</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">addmargins</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><p>In the first table, we observe the <code>South</code> has the most roller coasters according to this data set, at <span class="math inline">\(223\)</span>.</p></li>
<li><p>In the second table, we observe that of the <span class="math inline">\(160\)</span> total <code>Thrill</code> roller coasters, the fewest occurs in the <code>West</code>, at <span class="math inline">\(32\)</span>.</p></li>
<li><p>In the last table, we notice there aren’t any (i.e., <span class="math inline">\(0\)</span>) <code>Older</code> roller coasters in the <code>West</code> with a <code>Family</code> classification. Of the <code>Newest</code> roller coasters, the fewest occurs in the <code>Northeast</code> with <code>Kiddie</code> as <code>scale</code>.</p></li>
<li><p>Next we create a conditional two-way table on the <code>Newest</code> roller coasters for <code>scale</code> and <code>census_region</code>.</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>roller_coaster <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(age_group <span class="sc">==</span> <span class="st">"3:Newest"</span>) <span class="sc">|&gt;</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(census_region, scale) <span class="sc">|&gt;</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>() <span class="sc">|&gt;</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">addmargins</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             scale
census_region Extreme Family Kiddie Thrill Sum
    Midwest        34     21      4     13  72
    Northeast      37     29      1     20  87
    South          49     55      6     39 149
    West           27     20      3     18  68
    Sum           147    125     14     90 376</code></pre>
</div>
</div>
<p>Then we repeat this process by subsetting our previous three-way table.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>three_way[, , <span class="st">"3:Newest"</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           
            Extreme Family Kiddie Thrill Sum
  Midwest        34     21      4     13  72
  Northeast      37     29      1     20  87
  South          49     55      6     39 149
  West           27     20      3     18  68
  Sum           147    125     14     90 376</code></pre>
</div>
</div>
<ul>
<li>Then we create a two-way contingency table using <code>group_by</code> and <code>summarize</code> and <code>pivot_wider</code> to mimic the output of <code>table</code>.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>roller_coaster <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(census_region, scale) <span class="sc">|&gt;</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> scale, <span class="at">values_from =</span> count)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
# Groups:   census_region [4]
  census_region Extreme Family Kiddie Thrill
  &lt;fct&gt;           &lt;int&gt;  &lt;int&gt;  &lt;int&gt;  &lt;int&gt;
1 Midwest            61     32      8     33
2 Northeast          62     49      7     38
3 South              92     68      6     57
4 West               54     29      7     32</code></pre>
</div>
</div>
<ul>
<li>Now we begin to explore the data using graphs, starting with a stacked bar graph on <code>census_region</code> and <code>scale</code>.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> roller_coaster, <span class="fu">aes</span>(<span class="at">x =</span> census_region, <span class="at">fill =</span> scale)) <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Census Region"</span>, <span class="at">y =</span> <span class="st">"Quantity"</span>,</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Number of Roller Coasters"</span>,</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Stacked Bars"</span>) <span class="sc">+</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>       <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span> <span class="co"># centers titles</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>       <span class="fu">scale_fill_discrete</span>(<span class="st">"Scale"</span>) <span class="co"># Re-titles Legend</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw-4_files/figure-html/hw_4_task_2_response_05_part_1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From this graph we can see <code>South</code> dominates the roller coaster scene.</p>
<p>Now we construct a side-by-side bar graph, this time using <code>census_region</code> and <code>age_group</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> roller_coaster, <span class="fu">aes</span>(<span class="at">x =</span> census_region, <span class="at">fill =</span> age_group)) <span class="sc">+</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Census Region"</span>, <span class="at">y =</span> <span class="st">"Quantity"</span>,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Number of Roller Coasters"</span>,</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Side-by-Side Bar Plot"</span>) <span class="sc">+</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>       <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>       <span class="fu">scale_fill_discrete</span>(<span class="at">name =</span> <span class="st">"Age Group"</span>,</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>                           <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Older"</span>, <span class="st">"Recent"</span>, <span class="st">"Newest"</span>)) <span class="co"># Re-titles Categories</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw-4_files/figure-html/hw_4_task_2_response_05_part_2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>For once, another category beats out <code>South</code>: <code>Northeast</code> has the highest quantity of <code>Older</code> roller coasters, which may make sense given the spread of industrialization across the US.</p>
</section>
<section id="numeric-variables-and-across-groups" class="level2">
<h2 class="anchored" data-anchor-id="numeric-variables-and-across-groups">Numeric Variables (and across groups)</h2>
<p>For this section we will focus on the quantitative data from the roller coaster data set.</p>
<ol type="1">
<li>We begin by finding numeric summaries for <code>max_height</code> and <code>number_of_inversions</code>.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>roller_coaster <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">c</span>(max_height, number_of_inversions), </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">list</span>(<span class="st">"mean"</span> <span class="ot">=</span> <span class="er">~</span> <span class="fu">mean</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"median"</span> <span class="ot">=</span> <span class="er">~</span> <span class="fu">median</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"std_dev"</span> <span class="ot">=</span> <span class="er">~</span> <span class="fu">sd</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"IQR"</span> <span class="ot">=</span> <span class="er">~</span> <span class="fu">IQR</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)),</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">.names =</span> <span class="st">"{.fn}_{.col}"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">simplify</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             mean_max_height            median_max_height 
                  76.8039872                   64.3000000 
          std_dev_max_height               IQR_max_height 
                  61.5113686                   81.0000000 
   mean_number_of_inversions  median_number_of_inversions 
                   0.9212598                    0.0000000 
std_dev_number_of_inversions     IQR_number_of_inversions 
                   1.7725843                    1.0000000 </code></pre>
</div>
</div>
<p>Evidently, a majority of roller coasters in the US have no inversions (“loop-de-loops”), as the median indicates. Since <span class="math inline">\(\mu_{\text{max height}} &gt; Q_{2_{\text{max height}}}\)</span>, we may conclude the <code>max_heights</code> is skewed right (positively skewed), i.e., in the direction of the mean.</p>
<p>Now we repeat the analyses, looking at only those roller coasters whose scale is <code>Extreme</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>roller_coaster <span class="sc">|&gt;</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(scale <span class="sc">==</span> <span class="st">"Extreme"</span>) <span class="sc">|&gt;</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">c</span>(max_height, number_of_inversions), </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">list</span>(<span class="st">"mean"</span> <span class="ot">=</span> <span class="er">~</span> <span class="fu">mean</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"median"</span> <span class="ot">=</span> <span class="er">~</span> <span class="fu">median</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"std_dev"</span> <span class="ot">=</span> <span class="er">~</span> <span class="fu">sd</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"IQR"</span> <span class="ot">=</span> <span class="er">~</span> <span class="fu">IQR</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)),</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">.names =</span> <span class="st">"{.fn}_{.col}"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">simplify</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             mean_max_height            median_max_height 
                  126.495539                   110.000000 
          std_dev_max_height               IQR_max_height 
                   58.902617                    55.000000 
   mean_number_of_inversions  median_number_of_inversions 
                    2.174721                     2.000000 
std_dev_number_of_inversions     IQR_number_of_inversions 
                    2.167250                     4.000000 </code></pre>
</div>
</div>
<p>Restricted to this <code>scale</code>, the mean and median <code>max_height</code>s are arppoximately <span class="math inline">\(50\)</span> feet (?) greater. The right-skewness of <code>max_height</code> is maintained, but within this group we note there are, on average, <span class="math inline">\(2\)</span> inversions.</p>
<ol start="2" type="1">
<li>We repeat the analyses, grouping by <code>census_region</code>.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>roller_coaster <span class="sc">|&gt;</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(census_region) <span class="sc">|&gt;</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">c</span>(max_height, number_of_inversions), </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">list</span>(<span class="st">"mean"</span> <span class="ot">=</span> <span class="er">~</span> <span class="fu">mean</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"median"</span> <span class="ot">=</span> <span class="er">~</span> <span class="fu">median</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"std_dev"</span> <span class="ot">=</span> <span class="er">~</span> <span class="fu">sd</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"IQR"</span> <span class="ot">=</span> <span class="er">~</span> <span class="fu">IQR</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)),</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">.names =</span> <span class="st">"{.fn}_{.col}"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>) <span class="co"># prints all the columns</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 9
  census_region mean_max_height median_max_height std_dev_max_height
  &lt;fct&gt;                   &lt;dbl&gt;             &lt;dbl&gt;              &lt;dbl&gt;
1 Midwest                  84.2              74.4               68.6
2 Northeast                72.2              56                 60.8
3 South                    74.7              63.5               57.7
4 West                     78.4              68.5               61.0
  IQR_max_height mean_number_of_inversions median_number_of_inversions
           &lt;dbl&gt;                     &lt;dbl&gt;                       &lt;dbl&gt;
1           88.5                     0.866                           0
2           81.2                     0.885                           0
3           75.5                     0.937                           0
4           71.6                     1                               0
  std_dev_number_of_inversions IQR_number_of_inversions
                         &lt;dbl&gt;                    &lt;dbl&gt;
1                         1.69                        0
2                         1.80                        0
3                         1.79                        1
4                         1.80                        1</code></pre>
</div>
</div>
<p>This shows the <code>mean_height</code> is consistently skewed right across the regions of the US, with the tallest roller coasters appearing to be in the <code>Midwest</code>, also with the highest variation. While the median <code>number_of_inversions</code> is still <span class="math inline">\(0\)</span>, the <code>West</code> region appears to have the highest mean <code>number_of_inversions</code>.</p>
<ol start="3" type="1">
<li>We repeat the analyses, grouping by <code>census_region</code> and <code>scale</code>.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>roller_coaster <span class="sc">|&gt;</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(census_region, scale) <span class="sc">|&gt;</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">c</span>(max_height, number_of_inversions), </span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">list</span>(<span class="st">"mean"</span> <span class="ot">=</span> <span class="er">~</span> <span class="fu">mean</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"median"</span> <span class="ot">=</span> <span class="er">~</span> <span class="fu">median</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"std_dev"</span> <span class="ot">=</span> <span class="er">~</span> <span class="fu">sd</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"IQR"</span> <span class="ot">=</span> <span class="er">~</span> <span class="fu">IQR</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)),</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">.names =</span> <span class="st">"{.fn}_{.col}"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 16 × 10
# Groups:   census_region [4]
   census_region scale   mean_max_height median_max_height std_dev_max_height
   &lt;fct&gt;         &lt;fct&gt;             &lt;dbl&gt;             &lt;dbl&gt;              &lt;dbl&gt;
 1 Midwest       Extreme           137.              116.               62.9 
 2 Midwest       Family             20.7              14                14.2 
 3 Midwest       Kiddie             11                12                 1.85
 4 Midwest       Thrill             63.1              55                25.7 
 5 Northeast     Extreme           122.              110                62.1 
 6 Northeast     Family             28.7              17                27.2 
 7 Northeast     Kiddie             19.3              12                18.3 
 8 Northeast     Thrill             56.2              50                23.1 
 9 South         Extreme           125.              110.               52.0 
10 South         Family             27.4              17                22.1 
11 South         Kiddie             27                 8                48.0 
12 South         Thrill             54.2              49.3              20.5 
13 West          Extreme           123.              109.               61.6 
14 West          Family             30.1              26                24.4 
15 West          Kiddie             12.4              11                 3.32
16 West          Thrill             60.7              53.5              19.3 
   IQR_max_height mean_number_of_inversions median_number_of_inversions
            &lt;dbl&gt;                     &lt;dbl&gt;                       &lt;dbl&gt;
 1           67                        1.90                           1
 2           15.4                      0                              0
 3            1                        0                              0
 4           32.1                      0                              0
 5           44.5                      2.23                           2
 6           18                        0                              0
 7            5                        0                              0
 8           21.3                      0                              0
 9           55                        2.27                           2
10           24.4                      0                              0
11            0                        0                              0
12           26.6                      0                              0
13           60                        2.26                           2
14           28.7                      0                              0
15            3.6                      0                              0
16           22.8                      0                              0
   std_dev_number_of_inversions IQR_number_of_inversions
                          &lt;dbl&gt;                    &lt;dbl&gt;
 1                         2.09                     4   
 2                         0                        0   
 3                         0                        0   
 4                         0                        0   
 5                         2.29                     3.75
 6                         0                        0   
 7                         0                        0   
 8                         0                        0   
 9                         2.19                     4   
10                         0                        0   
11                         0                        0   
12                         0                        0   
13                         2.11                     3.75
14                         0                        0   
15                         0                        0   
16                         0                        0   </code></pre>
</div>
</div>
<p>This demonstrates that while the <code>Midwest</code> region appears to value <code>max_height</code> more than the other regions, the other regions appear to value <code>number_of_inversions</code> more than <code>Midwest</code>. Note there appears to be a correlation between the factor <code>Extreme</code> and <code>number_of_inversions</code>, as might be expected.</p>
<ol start="4" type="1">
<li>Next we craft a correlation matrix among all <span class="math inline">\(9\)</span> numeric variables.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>numeric_data <span class="ot">&lt;-</span> roller_coaster[, <span class="fu">sapply</span>(roller_coaster, is.numeric)] <span class="co"># returns just the portion of the data that is numeric</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(numeric_data, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     year_opened   top_speed  max_height        drop
year_opened           1.00000000  0.07523024  0.17444865  0.14880229
top_speed             0.07523024  1.00000000  0.89958035  0.91065440
max_height            0.17444865  0.89958035  1.00000000  0.95883038
drop                  0.14880229  0.91065440  0.95883038  1.00000000
length               -0.05230856  0.72958067  0.60634255  0.64206458
duration              0.01910470  0.33969411  0.26660184  0.26653819
number_of_inversions  0.16157407  0.33770901  0.31021683  0.29579170
latitude             -0.17756950 -0.03996281 -0.03385612 -0.01236978
longitude            -0.01615364 -0.01022347 -0.01197198  0.01322657
                          length    duration number_of_inversions    latitude
year_opened          -0.05230856  0.01910470           0.16157407 -0.17756950
top_speed             0.72958067  0.33969411           0.33770901 -0.03996281
max_height            0.60634255  0.26660184           0.31021683 -0.03385612
drop                  0.64206458  0.26653819           0.29579170 -0.01236978
length                1.00000000  0.50693203           0.19466332 -0.06284771
duration              0.50693203  1.00000000           0.10949861 -0.20229813
number_of_inversions  0.19466332  0.10949861           1.00000000 -0.05710304
latitude             -0.06284771 -0.20229813          -0.05710304  1.00000000
longitude             0.03497609 -0.06589117          -0.02087618  0.19340356
                       longitude
year_opened          -0.01615364
top_speed            -0.01022347
max_height           -0.01197198
drop                  0.01322657
length                0.03497609
duration             -0.06589117
number_of_inversions -0.02087618
latitude              0.19340356
longitude             1.00000000</code></pre>
</div>
</div>
<p>The strongest correlations appear between the <code>top_speed</code>, <code>max_height</code>, <code>drop</code>, and <code>length</code>, which from a physics standpoint makes sense, whereas the weakest correlations appear with the <code>latitude</code> and <code>longitude</code> variables. That makes sense because location should not have much impact on the other variables, and vice-versa.</p>
<ol start="5" type="1">
<li></li>
<li></li>
<li></li>
<li></li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>